@startuml
scale 1.1

skinparam {
backgroundColor white/#efe1ef

classBackgroundColor #accbe0\#eaf7fc
classbordercolor black

arrowColor #A80036

classFontSize 14
classFontStyle bold
classFontName Arial
classAttributeFontSize 14
classAttributeFontName calibri
}

hide class methods
hide class circle

class Клиент {
    ID :  Целое
    Серия и номер : Целое
    ФИО : Строка
    Телефон : Целое
}

class Заявка {
    ID : Целое
    Отправитель : Клиент
    Тип изделия : Строка
    Описание изделия : Строка
    Дата подачи заявки : Дата
    Статус заявки : Булево
}

class ЗаписьЖурнала {
    Дата подачи заявки : Дата
    Субъект : Клиент
    Тип издедия : Строка
    Статус верификации : Булево
}

class ЖурналВерификаций {
    Операции : Список <Запись журнала>
}

class Верификация {
  ID : Целое
  Тип изделия : Строка
  Описание изделия : Строка
}

class Патент {
    Название : Строка
    Статус верификации : Булево
}

class Оплата {
    ID заявки : Целое
    Субъект : Клиент
    Цена заявки : Дробное
    Цена патента : Дробное
}


Клиент " 1   " -- " 0..* " Заявка
Клиент " 1 " -- " 0..1    " Оплата

Верификация " 1..*   " -- " 1 " Клиент
ЗаписьЖурнала ..> Клиент
ЗаписьЖурнала .> Верификация

ЖурналВерификаций " 1 " o-- " 0..*  " ЗаписьЖурнала
Патент " 0..1  " -- " 1 " Верификация

@enduml